name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18, ubuntu-16]

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && sudo apt install libboost-all-dev libmsgpack-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build

  build-macos:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15, ubuntu-10.14]

        steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: brew update && brew install boost msgpack
        - name: configure
          run: mkdir build && cd build && cmake ..
        - name: build
          run: cmake --build build
