name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt install libmsgpack-dev
           echo $BOOST_ROOT
    - name: configure
      run: ./configure
    - name: make
      run: make
